apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  #ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: playwright
          image: gurvpk/playwright-test:__BUILD_NUMBER__
          imagePullPolicy: Always
          env:
            - name: ENV
              value: "qa"
            - name: BUILD_NUMBER
              value: "BUILD_NUMBER"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Never